### ISSUE TITLE
initially everything executes on all breakpoints

### ISSUE THREAD

**Issue by Saltibarsciai** [craigrileyuk/vue3-mq#1]
if I have
```
<mq-layout :mq="['sm']">
{{log('should not execute')}}
</mq-layout
```
and I am on desktop `log()` will execute. This causes a lot of double instances, for example click item which should create datepicker instance = creates 2 datepicker instances. Ofcourse workaround is to use flags, but flags are bad practice

**Comment by craigrileyuk** [comment]
I haven't been able to reproduce this issue, but I may have fixed whatever was causing it since it doesn't seem to be ocurring in the current build.

If you check https://vue3-mq.info/ you'll see I've put a console.log message to trigger when a 'sm' breakpoint is detected and it activates correctly.
