### ISSUE TITLE
<MqResponsive group> adding a div

### ISSUE THREAD

**Issue by demiro** [craigrileyuk/vue3-mq#22]
this code:
```
<MqResponsive group>
  <template #xs-sm>
    <button><IconMenu /></button>
  </template>
</MqResponsive>
```
is resulting in this:

```
<div data-v-30d3c9d3="" mode="out-in">
  <div>
    <button data-v-30d3c9d3=""><svg>...</svg></button>
  </div>
</div>
```

is there a way I can get them without the div wrappers?

**Comment by craigrileyuk** [comment]
In group mode, you can pass these two tags to `<MqResponse>`:

tag: string
list-tag: string

The first is the element tag that's used for the whole group, the second is the element tag used for each element in the group (which defaults to 'div').

The slot needs to render something because transitions won't work without an element wrapping them, but you could set `list-tag="button"` here and then just put your <svg> inside the slots.

I might look at including an 'abstract' mode for group lists in the future, but I've got a lot of paid projects to deal with at the moment which take priority.
