### ISSUE TITLE
Nuxt 3 SSR first loading

### ISSUE THREAD

**Issue by Bohdan909** [craigrileyuk/vue3-mq#24]
I noticed that there is a problem with detecting the breakpoint when the page is first loaded on SSR. 
I suspect that this is because the server default breakpoint does not match with the client breakpoint.

import { defineNuxtPlugin } from "#app";
import { Vue3Mq } from "vue3-mq";
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(Vue3Mq, {
    defaultBreakpoint: 'mobile',
      breakpoints: {
      mobile: 0,
      tabletSmall: 768,
      tablet: 960,
      desktop: 1025
    }
})
});

`<script setup>
import { useMq } from "vue3-mq"
const mq = useMq()
</script>
`

`<div :class="[{
          'fx': mq.desktop
        }]" />
`

`
        <Button
          v-if="mq.desktop"
        />
`

If my defaultBreakpoint: 'mobile' and page load on 'desktop' breakpoint condition 'mq.desktop' does not work :( 
And vice versa. 

The only solution I found is to wrap it in `<ClientOnly>`. But then there is no sense in SSR.
Is there any solution to this problem?

**Comment by craigrileyuk** [comment]
Vue 3.5 has introduced hydration mismatching which should be able to help with this in some situations: https://vuejs.org/api/ssr.html#data-allow-mismatch

I will, at some point, investigate a nuxt wrapper for this plugin that has the server take control of the 'defaultBreakpoint' since it has access to the requester's screen size.

Closing for now.
